### ISSUE TITLE
RFE: add custom template

### ISSUE THREAD

**Issue by drAlberT** [it-blaster/color-picker-type-bundle#3]
It would be nice to have a custom twig template in which the chosen color is displayed as background and not only as text

**Comment by fenrizbes** [comment]
I think you just need to configure a handler for Iris' `change` event and set the background color dynamically. For instance:

``` javascript
$(my_input).iris('option', 'change', function(e, ui) {
    $(this).css('background-color', ui.color.toString());
});
```

**Comment by drAlberT** [comment]
I'm talking about of something more structured ..  a type "color" to be used in list/show action for example

the "change" event could be included in normal behaviour of the bundle, but IMHO can be nice to have a "show color" form type too, in addiction to the "select color" already available

**Comment by drAlberT** [comment]
I mean .. you told "how", I'm asking to make this stuff work behind the curtain .. letting the coder to just configure the behaviour in the entity Admin class .. not having to trick JS by hand ;)

**Comment by drAlberT** [comment]
Ok I think I have found a clean solution.  If you think it is fine you could document it on your bundle too :)

```
            ->add('hexColor', 'color_picker', array(
                'label' => 'Color',
                'attr' => array(
                    'style' => 'border-left: 5px solid '.$this->getSubject()->getHexColor(),
                    'class' => 'admin-color-preview'
                ),
                'picker_options' => array(
                    'mode' => 'hsv',
                    'width' => '100',
                    'palettes' => array('#E5E4E2', '#FFD700', '#C0C0C0', '#75663F'),
                ),
            ))
```

**Comment by fenrizbes** [comment]
I think it's not particularly universal solution.
`$this->getSubject()` - I guess it's a SonataAdminBundle's feature only, isn't it?

**Comment by drAlberT** [comment]
You are right. It made my trick, but it's not optimal .. I'll make you know if I find a better solution, working outside sonata form too

Thank you

**Comment by drAlberT** [comment]
Ok the cleaner approach seems to append a class using _attr_ and then going on via css and JS as you suggested :)

Thank you

**Comment by fenrizbes** [comment]
You're welcome )
